---
title: "INDEX funModeling"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{INDEX funModeling}
  \usepackage[utf8]{inputenc}
---


Package funModeling
====

## Introduction

This package covers common aspects in predictive modeling:

+  A. **Data Preparation** / **Data Profiling**
+  B. **Selecting best variables (dataviz)**
+  C. **Assessing model performance**
+  D. **Miscellaneous**


As you can see, model creation is not included, while _almost_ everything else does. 

Model creation consumes around **10%** of almost any predictive modeling project; `funModeling` will try to cover remaining 90%. 

It´s not only the function itself, but the explanation of how to interpret results. This brings a deeper understanding of **what is being done**, boosting the freedom to use that knowledge in other situations andor using languages.


## `funModeling` quick start


### Part A: Data Preparation

Full info at: 

### Part B: Selecting best variables (dataviz)

```{r}


```

Full info at: 

### Part C: Assessing model performance

Full info at: 

### Part D: Miscellaneous

Full info at: 


