#' @title Discretize a data frame
#' @description Converts a numerical variable into factor or character, depending on 'stringsAsFactors' parameter.
#' Binning criteria is equal frequency.
#' The thresholds for each segment in each variable are generated with 'discretize_get_bins' function, which returns a data frame
#' that has to be the input in 'data_bins' parameter.
#' Important to note that the returned data frame contains the non-transformed variables plus the transformed ones.
#' More info about converting numerical into categorical variables can be found at: <https://livebook.datascienceheroes.com/data-preparation.html#data_types>
#' @param data Input data frame
#' @param data_bins data frame generated by 'discretize_get_bins' function. It contains the variable name and the thresholds for each bin, or segment.
#' @param stringsAsFactors Boolean variable which indicates if the discretization result is character or factor.
#' When TRUE, the segments are ordered. TRUE by default.
#' @examples
#' \dontrun{
#' # Getting the bins thresholds for each. If input is missing, will run for all numerical variables.
#' d_bins=discretize_get_bins(data=heart_disease, input=c("resting_blood_pressure", "oldpeak"), n_bins=5)
#'
#' # Now it can be applied on the same data frame, or in a new one (for example in a predictive model that change data over time)
#' heart_disease_discretized=discretize_df(data=heart_disease, data_bins=d_bins, stringsAsFactors=T)
#'
#'}
#' @return Data frame with the transformed variables
#' @export
discretize_df <- function(data, data_bins, stringsAsFactors=T)
{
	## Parte 2b: recover cuts
	vars_num=data_bins$variable

	for(i in vars_num)
	{
		v_orig=data[[i]]
		v_bins=filter(data_bins, variable==i)  %>% .$cuts
		v_res=dis_recover(x = v_orig, cuts = v_bins, stringsAsFactors = stringsAsFactors)

		data[[i]]=v_res
	}

	if(stringsAsFactors)
	{
		data_2b=data %>% mutate_at(vars(vars_num), conv_factor)
		data_3=data_2b %>% mutate_at(vars(vars_num), funs(factor(replace(., is.na(.), "NA."))))
	} else {
		data_3=data %>% mutate_at(vars(vars_num), funs(ifelse(is.na(.), "NA.", .)))
	}

	print(sprintf("Variables processed: %s", paste(vars_num, collapse = ", ")))

	return(data_3)
}

#' @title Get the cuts, or bin threshold, to discretize a variable.
#' @description It takes a data frame
#' @param data Data frame source
#' @param input Vector of string containing all the variables that will be processed.
#'  If empty it will run for all numerical variables. NAs values are automatically handled converting
#'  them into another category.
#' @param n_bins The number of bins (or segments) that each variable will have.
#' If it is needed a different number of bins per variable, then the function must be called more than once.
#' @examples
#' \dontrun{
#' # Getting the bins thresholds for each. If input is missing, will run for all numerical variables.
#' d_bins=discretize_get_bins(data=heart_disease, input=c("resting_blood_pressure", "oldpeak"), n_bins=5)
#'
#' # Now it can be applied on the same data frame, or in a new one (for example in a predictive model that change data over time)
#' heart_disease_discretized=discretize_df(data=heart_disease, data_bins=d_bins, stringsAsFactors=T)
#'
#'}
#' @return Data frame containing the thresholds or cuts to bin every variable
#' @export
discretize_get_bins <- function(data, input=NULL, n_bins=5)
{
	vars_num=df_status(data, print_results = F) %>% filter(type %in% c("integer","numeric"), unique>n_bins) %>% .$variable

	## If str_input then runs for all variables
	if(!missing(input))
	{
		vars_num=vars_num[vars_num %in% input]
	}

	d_bins=sapply(select(data, one_of(vars_num)), function(x) dis_bins(x, n_bins)) %>% as.data.frame(.)
	d_bins$variable=as.character(rownames(d_bins))
	d_bins=rename(d_bins, cuts='.') %>% select(variable, cuts)
	d_bins$cuts=as.character(d_bins$cuts)
	rownames(d_bins)=NULL

	print(sprintf("Variables processed: %s", paste(vars_num, collapse = ", ")))

	return(d_bins)
}

dis=function(x, n_bins)
{
	bins=discretize_bins(x, n_bins)
	res=discretize(x, "fixed", categories = bins)

	return(res)
}


get_bins_processed <- function(x, n_bins)
{
	cuts=discretize(x, "frequency", onlycuts = T, categories = n_bins)

	cuts[1]=-Inf
	cuts[length(cuts)]=Inf

	return(cuts)
}


dis_bins=function(x, n_bins=5, save_cuts=F)
{
	cuts=get_bins_processed(x, n_bins)
	res=paste(cuts, collapse = "|")

	names(x)
	colnames(x)

	return(res)
}


dis_recover <- function(x, cuts, stringsAsFactors)
{
	cuts_v=as.numeric(unlist(strsplit(cuts, '[|]')))
	x[x<min(cuts_v)]=min(cuts_v)
	x[x>max(cuts_v)]=max(cuts_v)

	res=arules::discretize(x, "fixed", categories = cuts_v)

	# Correction on "-Inf" label: [-Inf, min_value)
	if("-Inf" %in% levels(res))
	{
		cuts_v_aux=cuts_v[cuts_v!=-Inf]
		min_value=min(cuts_v_aux)
		levels(res)[levels(res)=="-Inf"]=sprintf("[-Inf, %s)", min_value)
	}
	########################


	if(!stringsAsFactors)
	{
		res=as.character(res)
	}

	return(res)
}

conv_factor <- function(x)
{
	levels(x)=c(levels(x), "NA.")
	new_x=factor(x, levels = levels(x))

	return(new_x)
}

